select * from dataset_1;
select weather,temperature from dataset_1;
select * from dataset_1 limit 10;
select distinct passanger from dataset_1;
select * from dataset_1 where destination='Home';
select * from dataset_1 order by coupon;
select destination as 'Destination' from dataset_1;
SELECT * FROM dataset_1;
select occupation from dataset_1 group by occupation;
select weather,avg(temperature) as temp from dataset_1 group by weather;
select weather,count(temperature) as count_temp from dataset_1 group by weather; 
select weather,count(DISTINCT temperature) as count_temp_disnt from dataset_1 group by weather; 
select weather,sum(temperature) as sum_temp from dataset_1 group by weather; 
select weather,min(temperature) as min_temp from dataset_1 group by weather; 
select weather,max(temperature) as max_temp from dataset_1 group by weather; 
select occupation from dataset_1 group by occupation having occupation='Student';
select * from dataset_1 union select * from table_to_union;
select DISTINCT destination from (select * from dataset_1 union select * from table_to_union);
select a.destination,a.time, b.part_of_day from dataset_1 a inner join table_to_join b on a.time=b.time;
select destination,passanger from (select * from dataset_1 where passanger='Alone');
select * from dataset_1 WHERE weather LIKE 'Sun%';
SELECT DISTINCT temperature from dataset_1 WHERE temperature BETWEEN 29 and 75;
SELECT occupation from dataset_1 WHERE occupation in ('Sales & Related','Management');